FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Nalle

Nalle is a simple API allowing developer to view state of Nalles and whereabouts in them.

# Manage the set of Teddybears [/nallar]

This resource manage the set or collective of nallar

## List all teddybears [GET]

+ Response 200 (text/plain)

    Hello World